services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: bitnami/pgbouncer:latest
    restart: unless-stopped
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_AUTH_TYPE: scram-sha-256
      PGBOUNCER_AUTH_TYPE: scram-sha-256
      POSTGRESQL_ADMIN_USERS: ${DB_USER},admin
    ports:
      - "5432:5432"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
